### ISSUE TITLE
Possible to include only certain Google Play Services libraries?

### ISSUE THREAD

**Issue by dwalintukan** [picatcha/adsnative-sdk-android#2]
Instead of including the entire Google Play Services library, is it possible to include only the necessary libraries?

If including the entire library, it puts my app over the 65K limit and requires MultiDex to be enabled.

**Comment by sreekanth-kalapur** [comment]
This has been addressed. Our SDK now requires only following GPS libraries to be included.
```
play-services-ads
play-services-location
```
